version: '3'

services:
    prixel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prixel
        ports:
            - 8023:8000
        volumes:
            - ./../:/var/www/symfony/
